apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-abacus-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abacus
  template:
    metadata:
      labels:
        app: abacus
    spec:
      containers:
      - name: abacus
        image: kittisuw/hello-abacus:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-abacus-service
spec:
  selector:
    app: abacus
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
